"""add ph_number to users table

Revision ID: 0078bf570dc7
Revises: a1a835641d28
Create Date: 2026-06-02 06:02:05.690004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0078bf570dc7'
down_revision = 'a1a835641d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ph_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ph_number')
    # ### end Alembic commands ###
